name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**.md'  # attiva solo se modificati file .md

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex

    - name: Convert Markdown to PDF
      run: |
        mkdir -p pdf
        find docs -name '*.md' | while read md; do
          pdf_name="pdf/$(basename "${md%.md}.pdf")"
          pandoc "$md" -o "$pdf_name" --pdf-engine=xelatex
        done

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdf-reports
        path: pdf/
